spring:
  application:
    name: demo
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb # 2. DB 접속 주소를 'testdb'로 고정
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true # 3. 실행되는 SQL 쿼리를 로그로 보여줌
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 줄바꿈 해줌